version: '3.9'

services:
  db:
    image: postgres:16
    container_name: market-db-local
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - marketplace-net



volumes:
  pgdata_local:

networks:
  marketplace-net:
    driver: bridge
