version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  db:
    image: postgres:16
    container_name: market-db-local
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data
    networks:
      - marketplace-net



volumes:
  pgdata_local:
  redis_data:

networks:
  marketplace-net:
    driver: bridge
